require:
  - rubocop-performance
  - rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/EmptyElse:
  EnforcedStyle: empty

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%w': '()'
    '%W': '()'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
