require:
  - rubocop-performance
  - rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/EmptyElse:
  EnforcedStyle: empty

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%r': '()'
    '%w': '()'
    '%W': '()'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/application.rb'

