version: "3"
services:
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=production
    command: "bundle exec puma -C config/puma.rb"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - RACK_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  db:
    image: redis:alpine
    ports:
      - "6379:6379"
